### ISSUE TITLE
Update to Nx Version 16

### ISSUE THREAD

**Issue by jasonbdt** [bennymeg/nx-electron#217]
**Is your feature request related to a problem? Please describe.**
No, there is no current problem related with.

**Describe the solution you'd like**
We already were very excited to develop our project with Nx Workspaces at v15. I think it would be good if we start to migrate as soon as possible to the latest release.

**Describe alternatives you've considered**
I think there's is no alternative

**Additional context**
- [Nx 16 is Here](https://blog.nrwl.io/nx-16-is-here-69584ec87053)
- [Rescope Packages from @nrwl to @nx](https://nx.dev/recipes/other/rescope)

**Tasks**
- [ ] Update code base to stop using methods that will be deprecated in future versions of Nx
- [ ] Update code base to fix `npm run test` (especially platform specific unit tests shouldn't fail)
- [ ] Update Nx to latest version

I've already forked the repository to make some changes. I'll try to help with this as much as possible✌️😉

**Comment by jasonbdt** [comment]
As Nx rescopes there official packages from `@nrwl/*` to `@nx/*` we need to wait, until the npm package [jest-preset-angular](https://www.npmjs.com/package/jest-preset-angular) updates to `v13.0.2` (see: https://github.com/thymikee/jest-preset-angular/pull/2061), as with `v13.0.1` the highest version of Angular we're able to use is `v15.2.9`.

`@nx/angular` versions history starts with `v16.0.0`

**Comment by jasonbdt** [comment]
As said above I've forked the repository and already made some changes. My first goal is to stop using methods that are already deprecated and will be removed in further versions of `@nx`. 

@bennymeg Are you available if I need help at fixing the unit tests of `nx-electron`? I might have some questions with this.

**Comment by AshkanYarmoradi** [comment]
Hi @bennymeg,
Any update for this migration?

**Comment by AshkanYarmoradi** [comment]
Please look at this PR; It's helpful #219

**Comment by abf7d** [comment]
I wanted to check in on this as well. I appreciate the work you are doing. Is there any recent update?

**Comment by bennymeg** [comment]
I haven't got a chance to verify the PR.
I will publish it tonight as an alpha so you could test it.

**Comment by mtrefzer** [comment]
Unable to use the recently released version `16.0.0-alpha`
I' getting the following error during `npm i` 
```
npm WARN Could not resolve dependency:
npm WARN peer @nx/workspace@"^15.9.2" from nx-electron@16.0.0-alpha.0
npm WARN node_modules/nx-electron
npm WARN   dev nx-electron@"^16.0.0-alpha.0" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nx/workspace@^15.9.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

```

**Comment by bennymeg** [comment]
@SouchetJulie Tnx, that was a mistake, I'll fix it
@mtrefzer, I think I know what the issue is, I'll fix it too tonight.

**Comment by mtrefzer** [comment]
@bennymeg tested version `16.0.0-alpha.1` and everything works perfectly fine. Thanks ;)

**Comment by mpellerin42** [comment]
@bennymeg I jusr tested version 16.0.0-alpha.1 as well and everything worked as expected. Thanks !

**Comment by mtrefzer** [comment]
@bennymeg I just noticed that `nx g nx-electron:app` is not working because of the missing implemetation in `nx-electron/src/generators/init/generator.ts`.
```
function setDefaultCollection(tree: Tree, arg1: string) {
  throw new Error('Function not implemented.');
}
```

**Comment by abf7d** [comment]
@bennymeg, I am getting `Function not implemented` as well. when I try using `nx g nx-electron:app`

**Comment by alkrobinson** [comment]
Serving works fine for the nx-electron@16.0.0-beta.0. But for some reason running the build directly produces the error below. Any ideas?

![5b1293d6-e950-45f3-8508-42f538eb4b98](https://github.com/bennymeg/nx-electron/assets/26122765/cff68f3a-fb59-426b-a783-d1c8f7ff475f)
![ac167e32-a280-4036-b8a7-4e8576d5f231](https://github.com/bennymeg/nx-electron/assets/26122765/9f813fea-0707-419d-9df8-01c53d9d89b5)

**Comment by WillPoulson** [comment]
@alkrobinson

It looks like something potentially introduced when develop was merged into the v16 feature branch. A sneeky little @nrwl import came back in.

As I already had a PR open I've just tacked that change onto the end #233 (Bad practice but it was a one liner!)

Not 100% sure if that'll resolve your issue here as I can't replicate myself, but it would add up.
What NX version are you attempting to use 16-beta with?

**Comment by bennymeg** [comment]
@WillPoulson Thanks! released a new fixed version.

**Comment by abf7d** [comment]
Hi @WillPoulson, I was able to generate a new electron app. There is an error I get in the console when I try to run it. It looks like it is running though. Here is the error I get:
```
Debugger listening on ws://127.0.0.1:5858/3b35a75e-d17a-499e-9ea7-bed2bdb2ecdf
For help, see: https://nodejs.org/en/docs/inspector

ERROR in apps/electron-shell/src/app/events/update.events.ts:38:27
TS2345: Argument of type '{ type: string; buttons: string[]; title: string; message: string; detail: 
string; }' is not assignable to parameter of type 'MessageBoxOptions'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type '"error" | "info" | "none" | "question" | "warning"'.    
    36 |     };
    37 |
  > 38 |     dialog.showMessageBox(dialogOpts).then(returnValue => {
       |                           ^^^^^^^^^^
    39 |         if (returnValue.response === 0) autoUpdater.quitAndInstall();
    40 |     });
    41 | });

```
Do you have any ideas on what this can be? Is this a typescript issue?
Thanks

**Comment by alkrobinson** [comment]
@WillPoulson I am on Nx version 16.5.3. The build issue is now resolved in `16.0.0-beta.1` but now I am getting errors in the make/package commands. It says it cannot find the built packages as soon as I run it. It doesn't seem to be packaging though. Any ideas?
![0abaaea0-1cea-4bbf-a7d9-e9210d430342](https://github.com/bennymeg/nx-electron/assets/26122765/e6a98b1b-f329-4ac2-9fcb-c6a0376979da)

**Comment by WillPoulson** [comment]
@alkrobinson Try running the :make command with `--sourcePath=dist/apps`. I encountered this same issue yesterday.

Another thing that slipped in from develop that isn't quite right with nx 16 I think.

I'll raise another PR to switch it back to use /apps by default and also attempt to resolve the issues that @abf7d ran into 👍

**Comment by abf7d** [comment]
Would we be able to get a publish? I apologize for the multiple requests.

**Comment by WillPoulson** [comment]
@abf7d Whilst waiting for the new version to be released, if you've got an existing generated project you can make the following changes to get the `update.events.ts` file to compile without any errors.

On line 1 add the import `MessageBoxOptions`.
(`import { app, autoUpdater, dialog, MessageBoxOptions } from 'electron';`)

And on line 31 set the type of the `dialogOpts` variable to `MessageBoxOptions`.
(`const dialogOpts: MessageBoxOptions = {`)

My PR modified the template files with these changes, so after it's released it would only fix _newly_ generated projects anyway.

Hope this is helpful to you, let me know if you've got any questions

**Comment by abf7d** [comment]
@WillPoulson, that worked! Thanks so much.

**Comment by dmatora** [comment]
tried `yarn add --dev github:WillPoulson/nx-electron#feature/resolve-nx-upgrade-issues`
still getting `NX   Unable to resolve nx-electron:app` on `nx g nx-electron:app desktop-electron` after that

**Comment by WillPoulson** [comment]
@dmatora I'd avoid using my forked version- there's additional fixes that came in branches afterwards. There's currently a [16.0.0-beta.1](https://www.npmjs.com/package/nx-electron/v/16.0.0-beta.1) version on npm which should be working.

This will need to be ran in an NX 16 project to work.

**Comment by dmatora** [comment]
@WillPoulson I was looking for this in girhub branches and tags, but couldn't find it.
Any clue how/why it's on npmjs only?

**Comment by dmatora** [comment]
Tried creating NX 16 project and using 16.0.0-beta.1 in it.
It throws `Cannot find module '@angular-devkit/core'`

**Comment by dmatora** [comment]
Not sure what's changed, but today I tried again and suddenly it worked
still requires `yarn add @nx/jest` and in the end it throws
```
 >  NX   File changes have already been written to disk. Further changes were attempted  while running generating (nx-electron:application).

   The file system can no longer be modified. This commonly happens when a generator attempts to make further changes in its callback, or an asynchronous operation is still running after the generator completes.


 >  NX   Tree changed after commit to disk.

   Pass --verbose to see the stacktrace.
```
but the project gets created and is functional

**Comment by dmatora** [comment]
Finally managed to get NX 16 working.
Created boilerplate in case anyone needs it https://github.com/dmatora/nx-electron-boilerplate

**Comment by bennymeg** [comment]
@dmatora why you added dependency for @nrwl/workspace: 15.9.2?

**Comment by dmatora** [comment]
without it, build for desktop-react or desktop-electron (don't remember which one, maybe both) was crashing

**Comment by dmatora** [comment]
however I just tried to reproduce the issue and couldn't
I've removed that commit from main and backed it up into separate branch

**Comment by bennymeg** [comment]
Released
